'use client';

import React from 'react';

interface SummarySidebarProps {
  isOpen: boolean;
  onClose: () => void;
  summary: string | null;
  loading: boolean;
  title?: string;
}

// Helper function to parse markdown bold syntax (**text**) and render as bold
const parseMarkdownBold = (text: string): React.ReactNode => {
  const parts: React.ReactNode[] = [];
  const regex = /\*\*(.*?)\*\*/g;
  let lastIndex = 0;
  let match;
  let keyCounter = 0;

  while ((match = regex.exec(text)) !== null) {
    // Add text before the match
    if (match.index > lastIndex) {
      const beforeText = text.substring(lastIndex, match.index);
      if (beforeText) {
        parts.push(<span key={`text-${keyCounter++}`}>{beforeText}</span>);
      }
    }
    // Add the bold text
    parts.push(<strong key={`bold-${keyCounter++}`}>{match[1]}</strong>);
    lastIndex = regex.lastIndex;
  }

  // Add remaining text
  if (lastIndex < text.length) {
    const remainingText = text.substring(lastIndex);
    if (remainingText) {
      parts.push(<span key={`text-${keyCounter++}`}>{remainingText}</span>);
    }
  }

  return parts.length > 0 ? <>{parts}</> : text;
};

export default function SummarySidebar({
  isOpen,
  onClose,
  summary,
  loading,
  title = 'AI Summary',
}: SummarySidebarProps) {
  if (!isOpen) return null;

  return (
    <aside className="w-80 bg-white border-l border-gray-200 shadow-lg flex flex-col h-full">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 flex items-center justify-between bg-[#E3F4F4]">
        <div>
          <h2 className="text-lg font-bold text-[#38598b]">{title}</h2>
          <p className="text-xs text-gray-500 mt-0.5">Generated by AI</p>
        </div>
        <button
          onClick={onClose}
          className="text-gray-500 hover:text-gray-700 transition-colors p-1 rounded hover:bg-gray-100"
          aria-label="Close summary"
        >
          <span className="text-xl">×</span>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-12">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#38598b] mb-4"></div>
            <p className="text-gray-600">Generating summary...</p>
          </div>
        ) : summary ? (
          <div className="prose max-w-none">
            <div className="whitespace-pre-wrap text-gray-700 leading-relaxed text-sm">
              {parseMarkdownBold(summary)}
            </div>
          </div>
        ) : (
          <div className="text-center text-gray-500 py-12">
            <p>No summary available</p>
          </div>
        )}
      </div>
    </aside>
  );
}

