'use client';

interface SummarySidebarProps {
  isOpen: boolean;
  onClose: () => void;
  summary: string | null;
  loading: boolean;
  title?: string;
}

export default function SummarySidebar({
  isOpen,
  onClose,
  summary,
  loading,
  title = 'AI Summary',
}: SummarySidebarProps) {
  if (!isOpen) return null;

  return (
    <aside className="w-80 bg-white border-l border-gray-200 shadow-lg flex flex-col h-full">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 flex items-center justify-between bg-[#E3F4F4]">
        <div>
          <h2 className="text-lg font-bold text-[#38598b]">{title}</h2>
          <p className="text-xs text-gray-500 mt-0.5">Generated by AI</p>
        </div>
        <button
          onClick={onClose}
          className="text-gray-500 hover:text-gray-700 transition-colors p-1 rounded hover:bg-gray-100"
          aria-label="Close summary"
        >
          <span className="text-xl">×</span>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-12">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#38598b] mb-4"></div>
            <p className="text-gray-600">Generating summary...</p>
          </div>
        ) : summary ? (
          <div className="prose max-w-none">
            <div className="whitespace-pre-wrap text-gray-700 leading-relaxed text-sm">
              {summary}
            </div>
          </div>
        ) : (
          <div className="text-center text-gray-500 py-12">
            <p>No summary available</p>
          </div>
        )}
      </div>
    </aside>
  );
}

