'use client';

interface SummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summary: string | null;
  loading: boolean;
  title?: string;
}

export default function SummaryModal({
  isOpen,
  onClose,
  summary,
  loading,
  title = 'AI Summary',
}: SummaryModalProps) {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="bg-white rounded-lg shadow-xl w-full max-w-3xl max-h-[80vh] overflow-hidden">
        {/* Header */}
        <div className="p-4 border-b border-gray-200">
          <h2 className="text-xl font-bold text-gray-800">{title}</h2>
          <p className="text-sm text-gray-500 mt-1">Generated by AI</p>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[60vh]">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#38598b] mb-4"></div>
              <p className="text-gray-600">Generating summary...</p>
            </div>
          ) : summary ? (
            <div className="prose max-w-none">
              <div className="whitespace-pre-wrap text-gray-700 leading-relaxed">
                {summary}
              </div>
            </div>
          ) : (
            <div className="text-center text-gray-500 py-12">
              <p>No summary available</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-gray-200 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-[#38598b] text-white rounded-lg hover:bg-[#2a4569] transition-colors font-medium shadow-md hover:shadow-lg"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

